version: "3.7"

services:
    php:
        container_name: web
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - fnsc.dev

networks:
    fnsc.dev:
        driver: bridge
